apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dummy-composition
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: DummyClaim
  mode: Pipeline
  pipeline:
    - step: load-environment-config
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: cluster-metadata
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: bucket
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  region: eu-west-1
    - step: render-template
      requirements:
        requiredResources:
        - requirementName: app-config-static
          apiVersion: v1
          kind: ConfigMap
          namespace: default
          name: simple-config
      input:
        test: parameter
      functionRef:
        name: function-debug
